baseURL = "https://blog.akashgirme.com"
languageCode = "en-us"
title = "Akash Girme's Blog"
paginate = 50
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-75485182-2"

[params]
subtitle = "Technology blog of India's largest stock broker"

[markup]
   [markup.goldmark.renderer]
      unsafe = true
